# Generated by Django 4.1.7 on 2023-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0003_alter_veiculo_ano_alter_veiculo_preco"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "Acessório", "verbose_name_plural": "Acessórios"},
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo", "verbose_name_plural": "Veículos"},
        ),
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
