# Generated by Django 4.1.7 on 2023-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_alter_acessorio_options_alter_cor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
    ]
