# Generated by Django 4.1.7 on 2023-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0006_modelo_categoria_modelo_marca_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="modelo",
        ),
    ]
