# Generated by Django 4.1.7 on 2023-04-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0007_remove_veiculo_categoria_remove_veiculo_marca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="garagem.modelo",
            ),
            preserve_default=False,
        ),
    ]
